### PR TITLE
correcting the shelter routes

### PR DESCRIPTION
**Pull request by KandasamyP**

### CODE REVIEW

**Review by prashantmall1997 — COMMENTED** [review]
Most likely shelter hbs and js are gonna break, you'll have to rectify that issue. Can't go through all changes, have my assignment and exam.

**Comment by KandasamyP** [comment]
> Most likely shelter hbs and js are gonna break, you'll have to rectify that issue. Can't go through all changes, have my assignment and exam.

shelter and rescue handlebars are displaying on my local, what piece of code you think  gonna break ?, so I can check it out

**Comment by prashantmall1997** [comment]
image
For example, there is a naming difference for the js file. So, it might work on your page but break on some other - like the signup page.

**Comment by KandasamyP** [comment]
> image
> For example, there is a naming difference for the js file. So, it might work on your page but break on some other - like the signup page.

actually; routes and data file name should be same; if we see for other functionality is same; so in signup page they have to change the filename

**Comment by KandasamyP** [comment]
> image
> For example, there is a naming difference for the js file. So, it might work on your page but break on some other - like the signup page.
are you doing signup page ?

**Pull request merged**
